name: Github Release

on:
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
